### PR TITLE
Add: 'tidy' command to Makefile

### PR DESCRIPTION
**Pull request by andygout**
cc @wheresrhys @adambraimbridge 

Is it bad form to have a test command that does nothing (even if it makes the CI pass)?

### CODE REVIEW

**Comment by matthew-andrews** [comment]
yup you can fix this in config vase

**Comment by wheresrhys** [comment]
fix how. I forgot to dig into this

**Comment by matthew-andrews** [comment]
is this project more of an npm component or more of an app?

**Comment by wheresrhys** [comment]
Initially I accidentally set up keen-query as an app in config vars. despite setting it to component shortly after, the make tidy lingered in circleci's settings. Have removed now and now the build passes ok

**Comment by wheresrhys** [comment]
but thanks for the PR :-)

**Comment by andygout** [comment]
Got it: Circle CI -> Project Settings -> Test commands -> Post-test commands - thanks!

**Pull request closed without merging**
